AllCops:
  TargetRubyVersion: 2.2
  Include:
    - '**/lib/'

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Description: Avoid methods longer than 20 lines of code.
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#short-methods
  Enabled: true
  CountComments: false
  Max: 20

Metrics/ParameterLists:
  Enabled: false
  Max: 5
  CountKeywordArgs: true

Style/BlockDelimiters:
  Enabled: false
